Repository redhat-beyond/BuyTogether, pull requests merged in 2023-01, with the labels that each got.

#55 Add client app
  buy_together/settings.py
  client/__init__.py
  client/admin.py
  client/apps.py
  client/migrations/0001_initial.py
  client/migrations/0002_test_data.py
  client/migrations/__init__.py
  client/models.py
  client/tests/test_client.py
  client/views.py
  conftest.py
Labels: Ready for review

#38 Add supplier product model
  buy_together/settings.py
  conftest.py
  supplier_product/__init__.py
  supplier_product/admin.py
  supplier_product/apps.py
  supplier_product/migrations/0001_initial.py
  supplier_product/migrations/0002_test_data.py
  supplier_product/migrations/__init__.py
  supplier_product/models.py
  supplier_product/tests.py
  supplier_product/views.py
Labels: Ready for review

#58 Add OrderdProduct module
  buy_together/settings.py
  conftest.py
  ordered_product/__init__.py
  ordered_product/admin.py
  ordered_product/apps.py
  ordered_product/migrations/0001_initial.py
  ordered_product/migrations/0002_test_data.py
  ordered_product/migrations/__init__.py
  ordered_product/models.py
  ordered_product/tests.py
  ordered_product/views.py
Labels: Ready for merge, Ready for review

#82 Fix product templates
  templates/product/help_parts/nav.html
  templates/product/products.html
Labels: Ready for merge

#85 Fix custom_user
  buy_together/settings.py
  buy_together_app/models.py
  client/admin.py
  client/migrations/0001_initial.py
  client/migrations/0002_test_data.py
  client/models.py
  client/tests/test_client.py
  conftest.py
  delivery_location/migrations/0001_initial.py
  delivery_location/migrations/0002_initial.py
  delivery_location/migrations/0002_test_data.py
  delivery_location/models.py
  delivery_location/tests/test_deliverylocation.py
  ordered_product/migrations/0001_initial.py
  ordered_product/migrations/0002_initial.py
  ordered_product/migrations/0002_test_data.py
  ordered_product/tests.py
  product/migrations/0002_test_data.py
  supplier/admin.py
  supplier/migrations/0001_initial.py
  supplier/migrations/0002_test_data.py
  supplier/models.py
  supplier/tests/test_supplier.py
  supplier_product/migrations/0001_initial.py
  supplier_product/migrations/0002_test_data.py
Labels: Ready for review

#88 Add signup for clients and suppliers
  buy_together_app/tests/test_sign_up.py
  buy_together_app/urls.py
  buy_together_app/views.py
  client/forms.py
  static/css/sign_up.css
  static/js/sign_up.js
  supplier/forms.py
  templates/buy_together_app/help_parts/nav.html
  templates/buy_together_app/sign_up.html
Labels: Ready for merge

#97 Add logout
  buy_together_app/tests/test_logout.py
  buy_together_app/urls.py
  buy_together_app/views.py
  templates/buy_together_app/help_parts/nav.html
Labels: Ready for review

#99 Add log_in tag in navbar
  templates/buy_together_app/help_parts/nav.html
Labels: Ready for review

#101 Add Suppler/client button
  buy_together_app/tests/test_main_page.py
  buy_together_app/views.py
  static/css/nav_bar.css
  templates/buy_together_app/help_parts/nav.html
Labels: enhancement, Ready for review, Simple

#91 Add supplier feature - display products
  static/css/suppliers.css
  supplier/tests/test_supplier_page.py
  supplier/views.py
  templates/buy_together_app/not_allowed.html
  templates/supplier/suppliers.html
Labels: enhancement, Ready for review

#84 Add ordered_product pages
  buy_together/urls.py
  conftest.py
  ordered_product/models.py
  ordered_product/tests/test_create_new_ordered_product.py
  ordered_product/tests/test_edit_ordered_product.py
  ordered_product/tests/test_ordered_product.py
  ordered_product/urls.py
  ordered_product/views.py
  static/css/new_order.css
  templates/ordered_product/new_order.html
  templates/ordered_product/pay_order.html
Labels: Ready for review

#94 Add client page
  buy_together/urls.py
  client/tests/test_client_page.py
  client/urls.py
  client/views.py
  static/css/clients.css
  templates/client/clients.html
Labels: Ready for review

#95 Add supplier page delivery feature
  static/css/suppliers.css
  supplier/tests/test_supplier_page.py
  supplier/views.py
  templates/supplier/suppliers.html
Labels: Ready for review

#106 Add links to LinkedIn
  templates/buy_together_app/description.html
Labels: Ready for merge, Simple
